/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FolderId = IDL.Text;
export const Timestamp = IDL.Int;
export const Folder = IDL.Record({
  'id' : FolderId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'parentId' : IDL.Opt(FolderId),
});
export const Tag = IDL.Text;
export const NoteId = IDL.Text;
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(Tag),
  'updatedAt' : Timestamp,
  'folderId' : IDL.Opt(FolderId),
});
export const NoteLink = IDL.Record({
  'toNoteId' : NoteId,
  'fromNoteId' : NoteId,
});
export const TagCount = IDL.Record({ 'tag' : Tag, 'count' : IDL.Nat });

export const idlService = IDL.Service({
  'createFolder' : IDL.Func([IDL.Text, IDL.Opt(FolderId)], [Folder], []),
  'createNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(FolderId), IDL.Vec(Tag)],
      [Note],
      [],
    ),
  'deleteFolder' : IDL.Func([FolderId], [IDL.Bool], []),
  'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getAllLinks' : IDL.Func([], [IDL.Vec(NoteLink)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllTags' : IDL.Func([], [IDL.Vec(TagCount)], ['query']),
  'getBacklinks' : IDL.Func([NoteId], [IDL.Vec(NoteLink)], ['query']),
  'getLinksByNote' : IDL.Func([NoteId], [IDL.Vec(NoteLink)], ['query']),
  'getNoteById' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'getNotesByFolder' : IDL.Func([FolderId], [IDL.Vec(Note)], ['query']),
  'getNotesByTag' : IDL.Func([Tag], [IDL.Vec(Note)], ['query']),
  'renameFolder' : IDL.Func([FolderId, IDL.Text], [IDL.Opt(Folder)], []),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'setNoteLinks' : IDL.Func([NoteId, IDL.Vec(NoteId)], [], []),
  'updateNote' : IDL.Func(
      [NoteId, IDL.Text, IDL.Text, IDL.Opt(FolderId), IDL.Vec(Tag)],
      [IDL.Opt(Note)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FolderId = IDL.Text;
  const Timestamp = IDL.Int;
  const Folder = IDL.Record({
    'id' : FolderId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'parentId' : IDL.Opt(FolderId),
  });
  const Tag = IDL.Text;
  const NoteId = IDL.Text;
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(Tag),
    'updatedAt' : Timestamp,
    'folderId' : IDL.Opt(FolderId),
  });
  const NoteLink = IDL.Record({ 'toNoteId' : NoteId, 'fromNoteId' : NoteId });
  const TagCount = IDL.Record({ 'tag' : Tag, 'count' : IDL.Nat });
  
  return IDL.Service({
    'createFolder' : IDL.Func([IDL.Text, IDL.Opt(FolderId)], [Folder], []),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(FolderId), IDL.Vec(Tag)],
        [Note],
        [],
      ),
    'deleteFolder' : IDL.Func([FolderId], [IDL.Bool], []),
    'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getAllLinks' : IDL.Func([], [IDL.Vec(NoteLink)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllTags' : IDL.Func([], [IDL.Vec(TagCount)], ['query']),
    'getBacklinks' : IDL.Func([NoteId], [IDL.Vec(NoteLink)], ['query']),
    'getLinksByNote' : IDL.Func([NoteId], [IDL.Vec(NoteLink)], ['query']),
    'getNoteById' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'getNotesByFolder' : IDL.Func([FolderId], [IDL.Vec(Note)], ['query']),
    'getNotesByTag' : IDL.Func([Tag], [IDL.Vec(Note)], ['query']),
    'renameFolder' : IDL.Func([FolderId, IDL.Text], [IDL.Opt(Folder)], []),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'setNoteLinks' : IDL.Func([NoteId, IDL.Vec(NoteId)], [], []),
    'updateNote' : IDL.Func(
        [NoteId, IDL.Text, IDL.Text, IDL.Opt(FolderId), IDL.Vec(Tag)],
        [IDL.Opt(Note)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };