/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Folder {
  'id' : FolderId,
  'name' : string,
  'createdAt' : Timestamp,
  'parentId' : [] | [FolderId],
}
export type FolderId = string;
export interface Note {
  'id' : NoteId,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'tags' : Array<Tag>,
  'updatedAt' : Timestamp,
  'folderId' : [] | [FolderId],
}
export type NoteId = string;
export interface NoteLink { 'toNoteId' : NoteId, 'fromNoteId' : NoteId }
export type Tag = string;
export interface TagCount { 'tag' : Tag, 'count' : bigint }
export type Timestamp = bigint;
export interface _SERVICE {
  'createFolder' : ActorMethod<[string, [] | [FolderId]], Folder>,
  'createNote' : ActorMethod<
    [string, string, [] | [FolderId], Array<Tag>],
    Note
  >,
  'deleteFolder' : ActorMethod<[FolderId], boolean>,
  'deleteNote' : ActorMethod<[NoteId], boolean>,
  'getAllFolders' : ActorMethod<[], Array<Folder>>,
  'getAllLinks' : ActorMethod<[], Array<NoteLink>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllTags' : ActorMethod<[], Array<TagCount>>,
  'getBacklinks' : ActorMethod<[NoteId], Array<NoteLink>>,
  'getLinksByNote' : ActorMethod<[NoteId], Array<NoteLink>>,
  'getNoteById' : ActorMethod<[NoteId], [] | [Note]>,
  'getNotesByFolder' : ActorMethod<[FolderId], Array<Note>>,
  'getNotesByTag' : ActorMethod<[Tag], Array<Note>>,
  'renameFolder' : ActorMethod<[FolderId, string], [] | [Folder]>,
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  'setNoteLinks' : ActorMethod<[NoteId, Array<NoteId>], undefined>,
  'updateNote' : ActorMethod<
    [NoteId, string, string, [] | [FolderId], Array<Tag>],
    [] | [Note]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];