/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type NoteId = string;
export type Tag = string;
export type Timestamp = bigint;
export interface Folder {
    id: FolderId;
    name: string;
    createdAt: Timestamp;
    parentId?: FolderId;
}
export interface TagCount {
    tag: Tag;
    count: bigint;
}
export interface NoteLink {
    toNoteId: NoteId;
    fromNoteId: NoteId;
}
export type FolderId = string;
export interface Note {
    id: NoteId;
    title: string;
    content: string;
    createdAt: Timestamp;
    tags: Array<Tag>;
    updatedAt: Timestamp;
    folderId?: FolderId;
}
export interface backendInterface {
    createFolder(name: string, parentId: FolderId | null): Promise<Folder>;
    createNote(title: string, content: string, folderId: FolderId | null, tags: Array<Tag>): Promise<Note>;
    deleteFolder(id: FolderId): Promise<boolean>;
    deleteNote(id: NoteId): Promise<boolean>;
    getAllFolders(): Promise<Array<Folder>>;
    getAllLinks(): Promise<Array<NoteLink>>;
    getAllNotes(): Promise<Array<Note>>;
    getAllTags(): Promise<Array<TagCount>>;
    getBacklinks(noteId: NoteId): Promise<Array<NoteLink>>;
    getLinksByNote(noteId: NoteId): Promise<Array<NoteLink>>;
    getNoteById(id: NoteId): Promise<Note | null>;
    getNotesByFolder(folderId: FolderId): Promise<Array<Note>>;
    getNotesByTag(tag: Tag): Promise<Array<Note>>;
    renameFolder(id: FolderId, name: string): Promise<Folder | null>;
    searchNotes(searchQuery: string): Promise<Array<Note>>;
    setNoteLinks(fromNoteId: NoteId, toNoteIds: Array<NoteId>): Promise<void>;
    updateNote(id: NoteId, title: string, content: string, folderId: FolderId | null, tags: Array<Tag>): Promise<Note | null>;
}
import type { Folder as _Folder, FolderId as _FolderId, Note as _Note, NoteId as _NoteId, Tag as _Tag, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createFolder(arg0: string, arg1: FolderId | null): Promise<Folder> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Folder_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Folder_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: string, arg1: string, arg2: FolderId | null, arg3: Array<Tag>): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Note_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Note_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFolder(arg0: FolderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async deleteNote(arg0: NoteId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getAllFolders(): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFolders();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFolders();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLinks(): Promise<Array<NoteLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLinks();
            return result;
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTags(): Promise<Array<TagCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTags();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTags();
            return result;
        }
    }
    async getBacklinks(arg0: NoteId): Promise<Array<NoteLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBacklinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBacklinks(arg0);
            return result;
        }
    }
    async getLinksByNote(arg0: NoteId): Promise<Array<NoteLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLinksByNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLinksByNote(arg0);
            return result;
        }
    }
    async getNoteById(arg0: NoteId): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoteById(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoteById(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByFolder(arg0: FolderId): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByFolder(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByFolder(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByTag(arg0: Tag): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByTag(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByTag(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameFolder(arg0: FolderId, arg1: string): Promise<Folder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameFolder(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameFolder(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchNotes(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNotes(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNotes(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setNoteLinks(arg0: NoteId, arg1: Array<NoteId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNoteLinks(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNoteLinks(arg0, arg1);
            return result;
        }
    }
    async updateNote(arg0: NoteId, arg1: string, arg2: string, arg3: FolderId | null, arg4: Array<Tag>): Promise<Note | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Folder_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Folder): Folder {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Folder]): Folder | null {
    return value.length === 0 ? null : from_candid_Folder_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FolderId]): FolderId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Note]): Note | null {
    return value.length === 0 ? null : from_candid_Note_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FolderId;
    name: string;
    createdAt: _Timestamp;
    parentId: [] | [_FolderId];
}): {
    id: FolderId;
    name: string;
    createdAt: Timestamp;
    parentId?: FolderId;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        parentId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoteId;
    title: string;
    content: string;
    createdAt: _Timestamp;
    tags: Array<_Tag>;
    updatedAt: _Timestamp;
    folderId: [] | [_FolderId];
}): {
    id: NoteId;
    title: string;
    content: string;
    createdAt: Timestamp;
    tags: Array<Tag>;
    updatedAt: Timestamp;
    folderId?: FolderId;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        tags: value.tags,
        updatedAt: value.updatedAt,
        folderId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.folderId))
    };
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Folder>): Array<Folder> {
    return value.map((x)=>from_candid_Folder_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n5(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FolderId | null): [] | [_FolderId] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
